services:
  grover:
    build: .
    container_name: grover-app
    volumes:
      - grover_db_data:/data
    env_file:
      - .env  # Load environment variables
    restart: unless-stopped
    ports:
      - "8003:5000"
    networks:
      - grover_apps_shared_network

networks:
  grover_apps_shared_network:
    external: true

volumes:
  grover_db_data:



